services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - stockflow-data:/app
    container_name: stockflow_backend

volumes:
  stockflow-data: