package main

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/tim/StockFlow/database"
	_ "github.com/tim/StockFlow/docs" // docs is generated by Swag CLI
	"github.com/tim/StockFlow/handlers"
	"github.com/tim/StockFlow/services"
)

// @title StockFlow API
// @version 1.0
// @description This is a sample server for a stock market simulator.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
func main() {
	database.InitDatabase()

	// Start the market simulation
	services.StartMarketSimulation()

	r := gin.Default()

	r.POST("/buy", handlers.BuyStock)
	r.POST("/sell", handlers.SellStock)
	r.GET("/portfolio/:user_id", handlers.GetPortfolio)
	r.GET("/balance/:user_id", handlers.GetBalance)

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":8080")
}
