basePath: /
definitions:
  handlers.BalanceResponse:
    properties:
      balance:
        type: number
    type: object
  handlers.BuyRequest:
    properties:
      limitPrice:
        description: Optional, for LIMIT orders
        type: number
      orderType:
        $ref: '#/definitions/models.OrderType'
      quantity:
        minimum: 1
        type: integer
      stockSymbol:
        type: string
      stopPrice:
        description: Optional, for STOP orders
        type: number
    required:
    - orderType
    - quantity
    - stockSymbol
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handlers.LoginResponse:
    properties:
      token:
        type: string
      username:
        type: string
    type: object
  handlers.PortfolioResponse:
    properties:
      portfolio:
        items:
          $ref: '#/definitions/models.Portfolio'
        type: array
      total_value:
        type: number
    type: object
  handlers.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handlers.RegisterResponse:
    properties:
      cash_balance:
        type: number
      token:
        type: string
      username:
        type: string
    type: object
  handlers.SellRequest:
    properties:
      limitPrice:
        description: Optional, for LIMIT orders
        type: number
      orderType:
        $ref: '#/definitions/models.OrderType'
      quantity:
        minimum: 1
        type: integer
      stockSymbol:
        type: string
      stopPrice:
        description: Optional, for STOP orders
        type: number
    required:
    - orderType
    - quantity
    - stockSymbol
    type: object
  handlers.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  models.OrderType:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - OrderTypeMarket
    - OrderTypeLimit
    - OrderTypeStop
  models.Portfolio:
    properties:
      quantity:
        type: integer
      stockSymbol:
        type: string
      userID:
        type: integer
    type: object
  types.StockSearchResult:
    properties:
      companyName:
        type: string
      symbol:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API for the StockFlow application.
  title: StockFlow API
  version: "1.0"
paths:
  /api/balance:
    get:
      description: Get a user's cash balance
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.BalanceResponse'
        "400":
          description: Invalid user ID
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get user balance
      tags:
      - portfolio
  /api/buy:
    post:
      consumes:
      - application/json
      description: Buy a specified quantity of a stock for a user
      parameters:
      - description: Buy Request
        in: body
        name: buy_request
        required: true
        schema:
          $ref: '#/definitions/handlers.BuyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully bought stock
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Buy a stock
      tags:
      - transactions
  /api/portfolio:
    get:
      description: Get a user's portfolio and total value
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PortfolioResponse'
        "400":
          description: Invalid user ID
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get user portfolio
      tags:
      - portfolio
  /api/sell:
    post:
      consumes:
      - application/json
      description: Sell a specified quantity of a stock for a user
      parameters:
      - description: Sell Request
        in: body
        name: sell_request
        required: true
        schema:
          $ref: '#/definitions/handlers.SellRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully sold stock
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Sell a stock
      tags:
      - transactions
  /api/stocks/search:
    get:
      description: Search for stock symbols or company names based on a query string
      parameters:
      - description: Search query for stock symbol or company name
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.StockSearchResult'
            type: array
        "400":
          description: Missing search query
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Search stocks
      tags:
      - stocks
  /auth/login:
    post:
      consumes:
      - application/json
      description: Log in a user with a username and password
      parameters:
      - description: User login info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LoginResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Failed to generate token
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Log in a user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with a username and password
      parameters:
      - description: User registration info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.RegisterResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Failed to create user
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Register a new user
      tags:
      - auth
  /health:
    get:
      description: Checks the health of the API and its dependencies (e.g., database).
      produces:
      - application/json
      responses:
        "200":
          description: API is healthy
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "500":
          description: API is unhealthy
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Health check
      tags:
      - health
swagger: "2.0"
